import type { Course, DemoUser, NetworkNode, WalletTransaction } from "@/lib/types";

export const demoUser: DemoUser = {
  id: "usr_elena",
  name: "Elena Voss",
  email: "elena.voss@lyra.app",
  avatar: null,
  role: "MEMBER",
  rank: "ALPHA",
  sponsorId: "usr_aurora",
};

export const demoTransactions: WalletTransaction[] = [
  {
    id: "txn_commission_week",
    description: "Comisión de equipo · semana 37",
    amountUsd: 640,
    creditDelta: 0,
    kind: "COMMISSION",
    createdAt: "2026-09-15T15:00:00.000Z",
  },
  {
    id: "txn_credit_pack",
    description: "Plan Negocio · 300 créditos",
    amountUsd: 99,
    creditDelta: 300,
    kind: "CREDIT_PURCHASE",
    createdAt: "2026-09-12T18:30:00.000Z",
  },
  {
    id: "txn_direct",
    description: "Comisión directa · Sofía Chen",
    amountUsd: 180,
    creditDelta: 0,
    kind: "COMMISSION",
    createdAt: "2026-09-08T11:10:00.000Z",
  },
  {
    id: "txn_copy",
    description: "Agente Copywriter · secuencia de historias",
    amountUsd: 0,
    creditDelta: -8,
    kind: "CREDIT_SPEND",
    createdAt: "2026-09-06T09:40:00.000Z",
  },
];

export const demoWallet = {
  balance: 1280,
  totalEarnedCommissions: 4820.5,
  transactions: demoTransactions,
};

export const networkTree: NetworkNode = {
  id: demoUser.id,
  name: demoUser.name,
  email: demoUser.email,
  rank: demoUser.rank,
  depth: 0,
  personalVolume: 1840,
  sponsorName: "Aurora Keene",
  children: [
    {
      id: "usr_mateo",
      name: "Mateo Ruiz",
      email: "mateo.ruiz@lyra.app",
      rank: "ASTRA",
      depth: 1,
      personalVolume: 420,
      sponsorName: "Elena Voss",
      children: [
        {
          id: "usr_ana",
          name: "Ana Sol",
          email: "ana.sol@lyra.app",
          rank: "ASTRA",
          depth: 2,
          personalVolume: 160,
          sponsorName: "Mateo Ruiz",
          children: [],
        },
        {
          id: "usr_leo",
          name: "Leo Kim",
          email: "leo.kim@lyra.app",
          rank: "ASTRA",
          depth: 2,
          personalVolume: 90,
          sponsorName: "Mateo Ruiz",
          children: [],
        },
      ],
    },
    {
      id: "usr_sofia",
      name: "Sofía Chen",
      email: "sofia.chen@lyra.app",
      rank: "ALPHA",
      depth: 1,
      personalVolume: 980,
      sponsorName: "Elena Voss",
      children: [
        {
          id: "usr_nora",
          name: "Nora Díaz",
          email: "nora.diaz@lyra.app",
          rank: "ASTRA",
          depth: 2,
          personalVolume: 240,
          sponsorName: "Sofía Chen",
          children: [],
        },
      ],
    },
    {
      id: "usr_ivan",
      name: "Iván Hale",
      email: "ivan.hale@lyra.app",
      rank: "ASTRA",
      depth: 1,
      personalVolume: 310,
      sponsorName: "Elena Voss",
      children: [],
    },
    {
      id: "usr_lina",
      name: "Lina Ortega",
      email: "lina.ortega@lyra.app",
      rank: "VEGA",
      depth: 1,
      personalVolume: 2120,
      sponsorName: "Elena Voss",
      children: [
        {
          id: "usr_gael",
          name: "Gael Mora",
          email: "gael.mora@lyra.app",
          rank: "ALPHA",
          depth: 2,
          personalVolume: 760,
          sponsorName: "Lina Ortega",
          children: [],
        },
      ],
    },
  ],
};

export const courses: Course[] = [
  {
    id: "crs_ia_fundamentos",
    title: "Qué es la IA y cómo piensa",
    description:
      "El punto de partida. Entiende qué es un modelo de lenguaje, cómo razona, por qué se equivoca y cómo pedirle bien desde el primer intento.",
    videoUrl: "lyra://academy/ia/fundamentos/intro",
    rankRequirement: "ASTRA",
    lessons: [
      {
        id: "les_ia_1",
        title: "Qué es un modelo de lenguaje",
        description: "La idea central de la IA moderna: predecir lo siguiente, no buscar en un libro.",
        videoUrl: "lyra://academy/ia/fundamentos/modelo",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ia_2",
        title: "Cómo razona y por qué se equivoca",
        description: "Patrones, contexto y alucinaciones: la diferencia entre sonar seguro y tener razón.",
        videoUrl: "lyra://academy/ia/fundamentos/razona",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ia_3",
        title: "El arte del prompt",
        description: "Rol, contexto, tarea y formato: la estructura que convierte una pregunta en un resultado.",
        videoUrl: "lyra://academy/ia/fundamentos/prompt",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ia_4",
        title: "Contexto vs. instrucción",
        description: "La diferencia clave entre decirle quién es y decirle qué hacer.",
        videoUrl: "lyra://academy/ia/fundamentos/contexto",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ia_5",
        title: "Tu primer contacto con Vega",
        description: "Abre el superagente, hazle una pregunta real y observa cómo responde.",
        videoUrl: "lyra://academy/ia/fundamentos/vega",
        rankRequirement: "ASTRA",
        completed: false,
      },
    ],
  },
  {
    id: "crs_ia_prompt",
    title: "Escribir prompts que sirven",
    description:
      "De la teoría a la práctica: aprende a iterar, verificar y convertir una instrucción vaga en un resultado útil para tu red.",
    videoUrl: "lyra://academy/ia/prompt/intro",
    rankRequirement: "ASTRA",
    lessons: [
      {
        id: "les_pr_1",
        title: "La estructura base",
        description: "La plantilla de cuatro partes que sirve para casi todo: rol, contexto, tarea y formato.",
        videoUrl: "lyra://academy/ia/prompt/estructura",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_pr_2",
        title: "Del vago al preciso",
        description: "Dos prompts lado a lado: por qué uno falla y el otro acierta.",
        videoUrl: "lyra://academy/ia/prompt/preciso",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_pr_3",
        title: "Iterar sin empezar de cero",
        description: "Cómo refinar una respuesta con seguimientos en lugar de reescribir todo.",
        videoUrl: "lyra://academy/ia/prompt/iterar",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_pr_4",
        title: "Verificar con criterio",
        description: "Cuándo confiar en la respuesta y cuándo comprobar antes de usarla.",
        videoUrl: "lyra://academy/ia/prompt/verificar",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_pr_5",
        title: "Práctica: un mensaje para tu red",
        description: "Construye un mensaje real con LYRA y guárdalo como plantilla.",
        videoUrl: "lyra://academy/ia/prompt/practica",
        rankRequirement: "ASTRA",
        completed: false,
      },
    ],
  },
  {
    id: "crs_ia_agentes",
    title: "Los agentes de la constelación",
    description:
      "LYRA tiene diez agentes, cada uno especializado. Aprende qué hace cada uno, cuándo usarlo y cómo vincular tus canales.",
    videoUrl: "lyra://academy/ia/agentes/intro",
    rankRequirement: "ASTRA",
    lessons: [
      {
        id: "les_ag_1",
        title: "Qué es un agente",
        description: "De la conversación única al especialista que ejecuta una tarea concreta.",
        videoUrl: "lyra://academy/ia/agentes/que-es",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ag_2",
        title: "Recepción y Prospector",
        description: "Abrir conversaciones: dudas, citas y el primer mensaje a un contacto nuevo.",
        videoUrl: "lyra://academy/ia/agentes/recepcion",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ag_3",
        title: "Copywriter y Comunidad",
        description: "Contenido y grupo: la pieza corta y el mensaje que mantiene viva la comunidad.",
        videoUrl: "lyra://academy/ia/agentes/copywriter",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ag_4",
        title: "Closer y Recordatorio",
        description: "Cerrar una conversación interesada y no dejar morir un seguimiento.",
        videoUrl: "lyra://academy/ia/agentes/closer",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ag_5",
        title: "Créditos y canales",
        description: "Cuánto cuesta cada ejecución y cómo vincular WhatsApp, correo o redes.",
        videoUrl: "lyra://academy/ia/agentes/creditos",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ag_6",
        title: "Práctica: tu primer agente en acción",
        description: "Elige un agente, vincúlalo a un canal y ejecútalo con contexto real.",
        videoUrl: "lyra://academy/ia/agentes/practica",
        rankRequirement: "ASTRA",
        completed: false,
      },
    ],
  },
  {
    id: "crs_ia_creativo",
    title: "Estudio creativo con IA",
    description:
      "De la idea al video: imagen, sonido y edición con IA para publicar sin perder tu voz.",
    videoUrl: "lyra://academy/ia/creativo/intro",
    rankRequirement: "ASTRA",
    lessons: [
      {
        id: "les_cr_1",
        title: "De la idea al video",
        description: "El flujo completo: concepto, guion breve, imagen y sonido.",
        videoUrl: "lyra://academy/ia/creativo/flujo",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_cr_2",
        title: "Prompts visuales",
        description: "Describir lo que imaginas para que la IA lo dibuje como lo ves en tu cabeza.",
        videoUrl: "lyra://academy/ia/creativo/visual",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_cr_3",
        title: "Edición y variaciones",
        description: "Tomar una pieza y multiplicarla en versiones para cada canal.",
        videoUrl: "lyra://academy/ia/creativo/edicion",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_cr_4",
        title: "Publicar sin perder tu voz",
        description: "Ajustar el resultado de la IA para que suene a ti, no a una máquina.",
        videoUrl: "lyra://academy/ia/creativo/voz",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_cr_5",
        title: "Práctica: una pieza lista",
        description: "Produce una pieza completa y déjala lista para tu red.",
        videoUrl: "lyra://academy/ia/creativo/practica",
        rankRequirement: "ASTRA",
        completed: false,
      },
    ],
  },
  {
    id: "crs_ia_negocio",
    title: "Notebook y Vega en tu negocio",
    description:
      "Investigación y delegación: haz que la IA lea tus fuentes y que Vega trabaje por ti sobre tu propia red.",
    videoUrl: "lyra://academy/ia/negocio/intro",
    rankRequirement: "ASTRA",
    lessons: [
      {
        id: "les_ne_1",
        title: "Notebook: investigar con IA",
        description: "Sube fuentes y hazles preguntas; la IA responde sobre tus documentos, no sobre internet.",
        videoUrl: "lyra://academy/ia/negocio/notebook",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ne_2",
        title: "Resumir sin perder el matiz",
        description: "Cómo pedir un resumen que conserve lo importante y deseche el ruido.",
        videoUrl: "lyra://academy/ia/negocio/resumir",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ne_3",
        title: "Qué hace Vega por ti",
        description: "El superagente que vende, atiende y cobra: alcance y límites.",
        videoUrl: "lyra://academy/ia/negocio/vega",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ne_4",
        title: "Enseñarle tu negocio",
        description: "La memoria de Vega: cómo darle el contexto que no debe olvidar.",
        videoUrl: "lyra://academy/ia/negocio/memoria",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ne_5",
        title: "Delegar tareas reales",
        description: "Del mensaje suelto a la tarea completa que Vega resuelve sola.",
        videoUrl: "lyra://academy/ia/negocio/delegar",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ne_6",
        title: "Práctica: automatizar tu semana",
        description: "Diseña una rutina semanal donde Vega hace el trabajo repetitivo.",
        videoUrl: "lyra://academy/ia/negocio/practica",
        rankRequirement: "ASTRA",
        completed: false,
      },
    ],
  },
  {
    id: "crs_ia_maestria",
    title: "Automatización y maestría",
    description:
      "El nivel experto: canales autónomos, construcción de agentes propios y orquestación de un equipo de IA que escala contigo.",
    videoUrl: "lyra://academy/ia/maestria/intro",
    rankRequirement: "ASTRA",
    lessons: [
      {
        id: "les_ma_1",
        title: "Telegram y canales autónomos",
        description: "Tu bot atendiendo prospectos mientras tú haces otra cosa.",
        videoUrl: "lyra://academy/ia/maestria/telegram",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ma_2",
        title: "Cuándo entra el humano",
        description: "El traspaso: el punto exacto donde el bot deja pasar a la persona.",
        videoUrl: "lyra://academy/ia/maestria/handoff",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ma_3",
        title: "Construir tu propio agente",
        description: "Anatomía de un agente en LYRA: rol, tono, límites y herramientas.",
        videoUrl: "lyra://academy/ia/maestria/agente",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ma_4",
        title: "Orquestar varios agentes",
        description: "Del agente suelto al sistema: repartir tareas entre especialistas.",
        videoUrl: "lyra://academy/ia/maestria/orquestar",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ma_5",
        title: "Ética y control",
        description: "Lo que un agente nunca debe hacer, y cómo supervisar su trabajo.",
        videoUrl: "lyra://academy/ia/maestria/etica",
        rankRequirement: "ASTRA",
        completed: false,
      },
      {
        id: "les_ma_6",
        title: "Capstone: tu equipo de IA",
        description: "Proyecto final: un sistema de agentes operando sobre tu red.",
        videoUrl: "lyra://academy/ia/maestria/capstone",
        rankRequirement: "ASTRA",
        completed: false,
      },
    ],
  },
];

export function countDirectAffiliates(node: NetworkNode = networkTree) {
  return node.children.length;
}
